# Generated by Django 5.1.6 on 2026-01-05 09:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('items', models.JSONField()),
                ('amount_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('payment_method', models.CharField(default='crypto', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TempCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('data', models.JSONField()),
            ],
        ),
    ]
